services:
  - type: web
    name: yarr
    region: frankfurt
    plan: starter
    runtime: docker
    repo: https://github.com/gagbo/yarr
    branch: autometrics
    dockerCommand: /usr/local/bin/yarr -addr 0.0.0.0:$PORT -db ./yarr.db
    envVars:
      - key: YARR_OTLP_COLLECTOR
        sync: false     # This value is set from Render dashboard
    disk:
      name: yarr
      mountPath: /data
      sizeGB: 3
