services:
  - type: web
    name: prometheus
    region: frankfurt
    plan: starter
    runtime: docker
    repo: https://github.com/gagbo/yarr-autometrics-deploy
    branch: main
    dockerfilePath: ./monitoring/prometheus/Dockerfile
    dockerContext: ./monitoring/prometheus
    dockerCommand: /bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles --web.enable-remote-write-receiver
    envVars:
      # Setting the PORT environment variable tells render that the service is
      # listening to 9090 It is important to set this value statically as it is
      # used in the prometheus/prometheus.yml config file.
      #
      # See https://github.com/autometrics-dev/render-prometheus for a more
      # complex blueprint component that will allow different configurations
      - key: PORT
        value: 9090
    disk:
      name: prometheus-tsdb
      mountPath: /prometheus
      sizeGB: 3

  - type: web
    name: otelcol
    region: frankfurt
    plan: starter
    runtime: docker
    repo: https://github.com/gagbo/yarr-autometrics-deploy
    branch: main
    dockerfilePath: ./monitoring/otelcol/Dockerfile
    dockerContext: ./monitoring/otelcol
    dockerCommand: /otelcol --config=/etc/otelcol/config.yaml
    envVars:
      # Setting the PORT environment variable tells render that the service is
      # listening to 4317 It is important to set this value statically as it is
      # used in the otelcol/otel-collector-config.yaml config file.
      - key: PORT
        value: 4317
