global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s
rule_files:
  - /etc/config/autometrics-rules.yml
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
